"""Generate Suricata rules from IP / domain / URL indicators."""
from __future__ import annotations

import hashlib
import pathlib

from ..normalize import detect_type, host_from_url

_NETWORK_KINDS = ("ipv4", "ipv6", "domain", "url")


def _sid_for(key: str, sid_base: int, used: set[int]) -> int:
    sid = sid_base + (int(hashlib.sha1(key.encode("utf-8")).hexdigest(), 16) % 900_000)
    while sid in used:
        sid += 1
    used.add(sid)
    return sid


def build_rules(rows, *, max_rules: int = 1500, sid_base: int = 9_100_000,
                min_confidence: int = 0) -> list[str]:
    entries: dict[str, tuple[str, str, str]] = {}  # key -> (kind, value, family)
    for row in rows:
        try:
            confidence = int(row["confidence"] or 0)
        except (TypeError, ValueError):
            confidence = 0
        if confidence < min_confidence:
            continue
        kind = row["type"]
        value = str(row["value"])
        if kind == "url":
            host = host_from_url(value)
            if not host:
                continue
            kind = detect_type(host) or "domain"
            value = host
        if kind not in _NETWORK_KINDS:
            continue
        family = str(row["malware"] or "").strip() or "unattributed"
        entry_key = f"{kind}:{value.lower()}"
        entries.setdefault(entry_key, (kind, value, family))
        if len(entries) >= max_rules:
            break

    used_sids: set[int] = set()
    lines: list[str] = []
    for entry_key, (kind, value, family) in sorted(entries.items()):
        sid = _sid_for(entry_key, sid_base, used_sids)
        message = f"TI {family} - {value}"
        if kind in ("ipv4", "ipv6"):
            lines.append(
                f'alert ip $HOME_NET any -> {value} any (msg:"{message}";'
                f" classtype:trojan-activity; sid:{sid}; rev:1;"
                " metadata:generated threat-intel-pipeline;)"
            )
        else:
            lines.append(
                f'alert dns any any -> any any (msg:"{message}";'
                f' dns.query; content:"{value}"; nocase; sid:{sid}; rev:1;'
                " metadata:generated threat-intel-pipeline;)"
            )
    return lines


def write_rules(lines: list[str], path: str | pathlib.Path) -> pathlib.Path:
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Suricata rules generated by threat-intel-pipeline.\n"
        "# Review false positives before enabling; assign your own sid range if\n"
        "# 9100000+ conflicts with local rules.\n"
    )
    body = "\n".join(lines) + ("\n" if lines else "")
    path.write_text(header + body, encoding="utf-8")
    return path
